---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Print env var
      ansible.builtin.debug:
        msg: "vpc name: '{{ lookup('env','VPC_NAME') }}'"

    - name: Get VPC id by name
      amazon.aws.ec2_vpc_net_info:
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        region: "{{ lookup('env', 'AWS_REGION' )}}"
        filters:
          "tag:Name": "{{ lookup('env','VPC_NAME') }}"
      register: vpc_info

    - name: Print return information from the previous task
      ansible.builtin.debug:
        msg: "vpc id: {{ vpc_info.vpcs[0].vpc_id }}"