---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - set_fact:
        ecr_url: "{{ lookup('env','ECR_URL') }}"

    - name: Create ecs service from ecr image
      include_role:
        name: deploy_service
      vars:
        service_name: "{{ app_name }}-ci-latest"
        image: "{{ ecr_url }}/{{ app_name }}"
        ecs_cluster_name: "{{ lookup('env','ECS_CLUSTER_NAME') }}"
